//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_de_aplicação.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Club
    {
        public Club()
        {
            this.Manager = new HashSet<Manager>();
            this.Player = new HashSet<Player>();
        }

        public int ClubID { get; set; }

        [Required]
        [Display(Name = "Club Name:")]
        public string ClubName { get; set; }

        [Required]
        [Display(Name = "Club Full Name:")]
        public string ClubFullName { get; set; }

        [Display(Name = "Country:")]
        public int CountryID { get; set; }

        [Required]
        [Display(Name = "Foundation Date:")]
        [RegularExpression(@"[0-9]{2}[\/]?[0-9]{2}[\/]?[0-9]{4}", ErrorMessage = "Invalid Date")]
        public string FoundationDate { get; set; }

        [Required]
        [Display(Name = "City Club:")]
        public string CityClub { get; set; }

        [Required]
        [Display(Name = "Price Merch:")]
        public decimal PriceMerch { get; set; }

        [Display(Name = "Image Shield:")]
        public byte[] ImageShield { get; set; }

        [Display(Name = "Club History:")]
        public string ClubHistory { get; set; }

        [Required]
        [Display(Name = "President:")]
        public string President { get; set; }

        [Required]
        [Display(Name = "Stadium:")]
        public string Stadium { get; set; }

        [Display(Name = "WebSite:")]
        public string WebSite { get; set; }

        public virtual ICollection<Manager> Manager { get; set; }
        public virtual ICollection<Player> Player { get; set; }

        [Display(Name = "Country:")]
        public virtual Country Country { get; set; }

        [NotMapped]
        public string GetLogo { get; set; }

        [NotMapped]
        public string GetFlagCountry { get; set; }
    }
}
