//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_de_aplicação.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Country
    {
        public Country()
        {
            this.Club = new HashSet<Club>();
            this.Manager = new HashSet<Manager>();
            this.Player = new HashSet<Player>();
        }

        public int CountryID { get; set; }

        [Display(Name = "Country:")]
        public string CountryName { get; set; }

        public byte[] Flag { get; set; }

        public virtual ICollection<Club> Club { get; set; }
        public virtual ICollection<Manager> Manager { get; set; }
        public virtual ICollection<Player> Player { get; set; }

        [NotMapped]
        public string GetFlagCountry { get; set; }


    }
}
