//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_de_aplicação.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PlayerStatus
    {
        public PlayerStatus()
        {
            this.Player = new HashSet<Player>();
        }

        public int PlayerStatusID { get; set; }

        [Display(Name = "Status:")]
        public string NameStatus { get; set; }

        public virtual ICollection<Player> Player { get; set; }
    }
}