//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_de_aplicação.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Player
    {
        public int PlayerID { get; set; }

        [Required]
        [Display(Name = "First Name:")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name:")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Name:")]
        public string NickName { get; set; }

        [Required]
        [Display(Name = "Date Of Birth:")]
        [RegularExpression(@"[0-9]{2}[\/]?[0-9]{2}[\/]?[0-9]{4}", ErrorMessage = "Invalid Date")]
        public string DateOfBirth { get; set; }

        [Required]
        [Display(Name = "Country:")]
        public int CountryID { get; set; }

        [Required]
        [Display(Name = "Position:")]
        public int PositionID { get; set; }

        [Required]
        [Display(Name = "Club:")]
        public int ClubID { get; set; }

        [Required]
        [Display(Name = "Status:")]
        public int PlayerStatusID { get; set; }

        [Display(Name = "Photo:")]
        public byte[] Photo { get; set; }

        [Display(Name = "Appearances:")]
        public Nullable<int> Appearances { get; set; }

        [Display(Name = "Yellow Card:")]
        public Nullable<int> YellowCard { get; set; }

        [Display(Name = "Red Card:")]
        public Nullable<int> RedCard { get; set; }

        [Display(Name = "Goals:")]
        public Nullable<int> GoalsScored { get; set; }

        [Display(Name = "Height:")]
        [RegularExpression(@"[0-9]{1}[\,]?[0-9]{2}")]
        public string Height { get; set; }

        [Required]
        [Display(Name = "Price Pass:")]
        public Nullable<decimal> PricePass { get; set; }

        [Display(Name = "Number:")]
        public Nullable<int> Number { get; set; }

        [Display(Name = "Club:")]
        public virtual Club Club { get; set; }

        [Display(Name = "Country:")]
        public virtual Country Country { get; set; }

        [Display(Name = "Player Status:")]
        public virtual PlayerStatus PlayerStatus { get; set; }

        [Display(Name = "Position:")]
        public virtual Position Position { get; set; }

        [NotMapped]
        public string GetPhoto { get; set; }

        [NotMapped]
        public string GetFlagCountry { get; set; }

        [NotMapped]
        public int Age { get; set; }
    }
}

