//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_de_aplicação.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Position
    {
        public Position()
        {
            this.Player = new HashSet<Player>();
        }

        public int PositionID { get; set; }

        [Display(Name = "Position:")]
        public string Position1 { get; set; }

        public virtual ICollection<Player> Player { get; set; }
    }
}

