//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_de_aplicação.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UEFAEntities : DbContext
    {
        public UEFAEntities()
            : base("name=UEFAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Club> Club { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<Manager> Manager { get; set; }
        public DbSet<Player> Player { get; set; }
        public DbSet<PlayerStatus> PlayerStatus { get; set; }
        public DbSet<Position> Position { get; set; }
        public DbSet<RoleType> RoleType { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UserStatus> UserStatus { get; set; }
    }
}
