//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_de_aplicação.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatus
    {
        public UserStatus()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int StatusID { get; set; }
        public string StatusDesc { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
